### ISSUE TITLE
What the heck is wrong with the code coverage report??

### ISSUE THREAD

**Issue by taylorn16** [taylorn16/fp-toolkit#30]

**Comment by rmjohnson** [comment]
We figured out its because we're exporting the functions twice (so they look sane in the docs). Once via just the `export const` inline and then at the bottom with `export const FooThing = { ... }` and only the latter is covered in tests.

To address this we should use the inline versions of the functions in the tests and then have c8 ignore the exported object at the bottom with all the functions.

**Comment by taylorn16** [comment]
Addressed as part of #34
